version: "2"

sql:
  - engine: "postgresql"
    schema: "../repo/schema"
    queries: "../repo/query"
    gen:
      go:
        package: "db"
        out: "../repo/db"
        sql_package: "pgx/v5"
        emit_interface: false
        emit_json_tags: true
        overrides:
          - db_type: "uuid"
            go_type: "github.com/google/uuid.UUID"

